name: Lab4 CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    outputs:
      improved: ${{ steps.compare.outputs.improved }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model
        run: |
          python train.py

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: outputs/*.pkl

      - name: Upload metrics artifact
        uses: actions/upload-artifact@v4
        with:
          name: metrics
          path: outputs/results.json

      - name: Compare metrics
        id: compare
        run: |
          BEST_R2=$(jq '[.[] | .r2] | max' outputs/results.json)
          BEST_MSE=$(jq '[.[] | .mse] | min' outputs/results.json)

          echo "New BEST_R2=$BEST_R2"
          echo "New BEST_MSE=$BEST_MSE"
          echo "OLD_R2=${{ vars.BEST_R2 }}"
          echo "OLD_MSE=${{ vars.BEST_MSE }}"

          if (( $(echo "$BEST_R2 > ${{ vars.BEST_R2 }}" | bc -l) )) && \
             (( $(echo "$BEST_MSE < ${{ vars.BEST_MSE }}" | bc -l) )); then
            echo "improved=true" >> $GITHUB_OUTPUT
          else
            echo "improved=false" >> $GITHUB_OUTPUT
          fi

      - name: Metric not improved
        if: steps.compare.outputs.improved == 'false'
        run: |
          echo "2022BCS0002 ---- Metric did not improve"

  deploy:
    needs: train
    if: needs.train.outputs.improved == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download model artifacts
        uses: actions/download-artifact@v4
        with:
          name: models

      - name: Download metrics artifact
        uses: actions/download-artifact@v4
        with:
          name: metrics

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/wine-inference:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/wine-inference:latest
